[versions]
accompanistPermissions = "0.37.2"
activityCompose = "1.10.1"
agp = "8.9.2"
compose = "2.1.2"
composeBom = "2025.04.01"
coreKtx = "1.16.0"
datastorePreferences = "1.2.0-alpha01"
espressoCore = "3.6.1"
glance = "1.1.1"
hiltAndroid = "2.56.2"
hiltAndroidCompiler = "2.56.2"
hiltNavigationCompose = "1.2.0"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlin = "2.1.20"
kotlinxCoroutinesAndroid = "1.10.2"
kotlinxCoroutinesPlayServices = "1.10.2"
kotlinxDatetime = "0.6.2"
kotlinxSerializationJson = "1.8.1"
ktorClientAndroid = "3.1.2"
ktorClientContentNegotiation = "3.1.2"
ktorClientLogging = "3.1.2"
lifecycleRuntimeKtx = "2.8.7"
materialIconsExtended = "1.7.8"
navigationCompose = "2.8.9"
playServicesLocation = "21.3.0"
roomCompiler = "2.7.1"
roomKtx = "2.7.1"
roomRuntime = "2.7.1"
slf4jSimple = "2.0.17"
workRuntimeKtx = "2.10.1"
vico = "2.1.2"
systemuicontroller = "0.36.0"

[libraries]
# For Jetpack Compose.
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "datastorePreferences" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastorePreferences" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
jetbrains-kotlinx-coroutines-play-services = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutinesPlayServices" }
play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4jSimple" }

# For Material 3 theming in Jetpack Compose.
vico-compose-m3 = { group = "com.patrykandpatrick.vico", name = "compose-m3", version.ref = "vico" }

# For the Android view system.
vico-views = { group = "com.patrykandpatrick.vico", name = "views", version.ref = "vico" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "systemuicontroller" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-hilt-common = { module = "androidx.hilt:hilt-common", version.ref = "hiltNavigationCompose" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hiltNavigationCompose" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-m3 = { module = "com.patrykandpatrick.vico:compose-m3", version.ref = "compose" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
glance = { module = "androidx.glance:glance", version.ref = "glance" }
glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "glance" }
glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "glance" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktorClientAndroid" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktorClientLogging" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientContentNegotiation" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktorClientLogging" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorClientContentNegotiation" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
material3 = { module = "androidx.compose.material3:material3" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
ui = { module = "androidx.compose.ui:ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest", version = "1.8.0" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

